# Generated by Django 2.0.13 on 2019-08-08 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190808_0021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='authr',
            new_name='autor',
        ),
    ]
